# Generated by Django 4.0.6 on 2022-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=4, verbose_name='Credits'),
            preserve_default=False,
        ),
    ]
