# Generated by Django 4.0.6 on 2022-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_marks',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='qb_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Question Bank Code'),
        ),
    ]
