# Generated by Django 4.0.6 on 2022-08-07 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_quiz_grade_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 16, 40, 32, 181213), verbose_name='Due Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
